//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Proyecto ED.rc
//
#define DLG_LOGIN_USER                  101
#define DLG_REGISTER_USER               103
#define DLG_PRINCIPAL                   105
#define IDR_MENU1                       107
#define DLG_REG_PERSON                  108
#define DLG_RE_VACUNA                   112
#define DLG_DELETE_VACUNA               116
#define DLG_BAJA_PERSONAS               118
#define DLG_CHANGE_VACCINE              120
#define DLG_CHANGE_PERSON               122
#define IDD_DIALOG1                     124
#define DLG_REG_CARNET                  124
#define DLG_DELETE_CARNET               126
#define DLG_CHANGE_CARNET               128
#define DLG_REPORTE_HEAPSORT            130
#define DLG_REPORTE_QUICKSORT           132
#define BTN_RETURN_LOGIN                1001
#define BTN_OK_LOGIN                    1002
#define TXT_CLAVE_LOGIN                 1004
#define ST_CLAVE_LOGIN                  1005
#define ST_CONTRA_LOGIN                 1006
#define TXT_CONTRA_LOGIN                1007
#define BTN_OK_REGISTER                 1008
#define TXT_CLAVE_RE                    1009
#define TXT_CONTRA_RE                   1010
#define TXT_AM_RE                       1011
#define TXT_AP_RE                       1012
#define TXT_NAME_RE                     1013
#define ST_CLA_RE                       1014
#define ST_CONT_RE                      1015
#define ST_AP_RE                        1016
#define ST_AM_RE                        1017
#define ST_NAME_RE                      1018
#define ST_WELCOME_PRIN                 1019
#define ST_USER_PRIN                    1020
#define BTN_RETURN_REGISTER             1021
#define TXT_AM_RE_PERSON                1022
#define TXT_NAME_RE_PERSON              1023
#define TXT_CURP_RE_PERSON              1024
#define TXT_RFC_RE_PERSON               1025
#define DTP_FECHA_RE_PERSON             1026
#define TXT_TELEFO_RE_PERSON            1027
#define TXT_ESTADO_RE_PERSON            1029
#define TXT_COLONIA_RE_PERSON           1030
#define TXT_CIUDAD_RE_PERSON            1031
#define TXT_CALLE_RE_PERSON             1032
#define CB_SEXO_RE_PERSON               1033
#define CB_PERFIL_RE_PERSON             1034
#define TXT_GRUPO_RE_PERSON             1035
#define BTN_CARG_RE_PERSON              1036
#define TXT_CENTRO_RE_CARNET            1036
#define BTN_OK_RE_PERSON                1037
#define CB_CIVIL_RE_PERSON              1038
#define BM_IMAGE_RE_PERSON              1039
#define ST_AP_RE_PERSON                 1040
#define ST_AM_RE_PERSON                 1041
#define ST_NAME_RE_PERSON               1042
#define ST_CURP_RE_PERSON               1043
#define ST_RFC_RE_PERSON                1044
#define ST_FECHA_RE_PERSON              1045
#define ST_CALLE_RE_PERSON              1046
#define ST_COL_RE_PERSON                1047
#define ST_CIUDAD_RE_PERSON             1048
#define ST_ESTADO_RE_PERSON             1049
#define ST_CIVIL_RE_PERSON              1050
#define ST_TELEFO_RE_PERSON             1051
#define ST_SEXO_RE_PERSON               1052
#define ST_GRUPO_RE_PERSON              1053
#define ST_PERFIL_RE_PERSON             1054
#define ST_IMAGE_RE_PERSON              1055
#define TXT_AP_RE_PERSON                1056
#define TXT_CIVIL_PERSONDELETE          1057
#define CB_IDENTIDAD_RE_PERSON          1057
#define CB_MARCA_VACUNA                 1058
#define ST_IDENTIDAD_RE_PERSON          1058
#define TXT_CLAVE_VACUNA                1059
#define TXT_DES_VACUNA                  1060
#define TXT_PRECIO_VACUNA               1061
#define BTN_OK_RE_VACUNA                1062
#define TXT_FECHAVACU1_RE_CARNET        1062
#define ST_TIPO_VACUNA                  1063
#define ST_MARCA_VACUNA                 1064
#define ST_DOSIS                        1065
#define ST_CLAVE_VACUNA                 1066
#define ST_DES_VACUNA                   1067
#define ST_PRECIO_VACUNA                1068
#define TXT_DOSIS_VACUNA                1069
#define TXT_MARCA_VACUNA                1070
#define TXT_TIPO_VACUNA                 1071
#define LB_VACUNA_DELETE                1072
#define ST_FECHAVACU1_RE_CARNET         1072
#define ST_TIPO_VACUNADELETE            1073
#define ST_FECHAVACU2_RE_CARNET         1073
#define ST_MARCA_VACUNADELETE           1074
#define ST_DOSIS_VACUNADELETE           1075
#define TXT_ID_RE_CARNET                1075
#define ST_CLAVE_VACUNADELETE           1076
#define TXT_IDENTITI_RE_CARNET          1076
#define ST_DES_VACUNADELETE             1077
#define ST_PRECIO_VACUNADELETE          1078
#define TXT_TIPO_VACUNADELETE           1079
#define TXT_MARCA_VACUNADELETE          1080
#define TXT_DOSIS_VACUNADELETE          1081
#define TXT_CLAVE_VACUNADELETE          1082
#define TXT_DES_VACUNADELETE            1083
#define TXT_PRECIO_VACUNADELETE         1084
#define ST_DELETE_LB                    1085
#define BTN_OK_VACUNADELETE             1086
#define LB_DELETE_PERSON                1087
#define ST_TEXTONAMAS                   1088
#define TXT_AP_PERSONDELETE             1089
#define ST_AP_RE_PERSONDELETE           1090
#define ST_AM_RE_PERSONDELETE           1091
#define ST_NAME_RE_PERSONDELETE         1092
#define ST_CURP_RE_PERSONDELETE         1093
#define ST_RFC_RE_PERSONDELETE          1094
#define ST_FECHA_RE_PERSONDELETE        1095
#define ST_CALLE_RE_PERSONDELETE        1096
#define ST_COL_RE_PERSONDELETE          1097
#define ST_CIUDAD_RE_PERSONDELETE       1098
#define ST_ESTADO_RE_PERSONDELETE       1099
#define ST_CIVIL_RE_PERSONDELETE        1100
#define ST_TELEFO_RE_PERSONDELETE       1101
#define ST_SEXO_RE_PERSONDELETE         1102
#define ST_GRUPO_RE_PERSONDELETE        1103
#define ST_PERFIL_RE_PERSONDELETE       1104
#define BM_IMAGE_PERSONDELETE           1105
#define ST_IMAGE_RE_PERSONDELETE        1106
#define TXT_AM_PERSONDELETE             1107
#define TXT_NAME_PERSONDELETE           1108
#define TXT_CURP_PERSONDELETE           1109
#define TXT_RFC_PERSONDELETE            1110
#define TXT_CALLE_PERSONDELETE          1111
#define TXT_COLONIA_PERSONDELETE        1112
#define TXT_CIUDAD_PERSONDELETE         1113
#define TXT_ESTADO_PERSONDELETE         1114
#define TXT_TELEFO_PERSONDELETE         1115
#define TXT_GRUPO_PERSONDELETE          1116
#define BTN_OK_PERSONDELETE             1117
#define ST_TIPO_VACUNACHANGE            1118
#define ST_IDENTIDAD_RE_PERSONDELETE    1118
#define ST_MARCA_VACUNACHANGE           1119
#define ST_DOSIS_VACUNACHANGE           1120
#define ST_CLAVE_VACUNACHANGE           1121
#define ST_DES_VACUNACHANGE             1122
#define ST_PRECIO_VACUNACHANGE          1123
#define ST_CHANGE_LB                    1124
#define BTN_OK_VACUNACHANGE             1125
#define LB_VACUNA_CHANGE                1126
#define TXT_TIPO_VACUNACHANGE           1127
#define TXT_MARCA_VACUNACHANGE          1128
#define TXT_DOSIS_VACUNACHANGE          1129
#define TXT_CLAVE_VACUNACHANGE          1130
#define TXT_DES_VACUNACHANGE            1131
#define TXT_PRECIO_VACUNACHANGE         1132
#define ST_AP_RE_PERSONCHANGE           1133
#define ST_AM_RE_PERSONCHANGE           1134
#define ST_NAME_RE_PERSONCHANGE         1135
#define TXT_AP_PERSONCHANGE             1136
#define TXT_AM_PERSONCHANGE             1137
#define TXT_NAME_PERSONCHANGE           1138
#define ST_CURP_RE_PERSONCHANGE         1139
#define TXT_CURP_PERSONCHANGE           1140
#define ST_RFC_RE_PERSONCHANGE          1141
#define TXT_RFC_PERSONCHANGE            1142
#define ST_FECHA_RE_PERSONCHANGE        1143
#define TXT_FECHA_PERSONCHANGE          1144
#define ST_CALLE_RE_PERSONCHANGE        1145
#define TXT_CALLE_PERSONCHANGE          1146
#define ST_COL_RE_PERSONCHANGE          1147
#define TXT_COLONIA_PERSONCHANGE        1148
#define ST_CIUDAD_RE_PERSONCHANGE       1149
#define TXT_CIUDAD_PERSONCHANGE         1150
#define ST_ESTADO_RE_PERSONCHANGE       1151
#define TXT_ESTADO_PERSONCHANGE         1152
#define ST_CIVIL_RE_PERSONCHANGE        1153
#define TXT_CIVIL_PERSONCHANGE          1154
#define ST_TELEFO_RE_PERSONCHANGE       1155
#define TXT_TELEFO_PERSONCHANGE         1156
#define ST_SEXO_RE_PERSONCHANGE         1157
#define TXT_SEXO_PERSONCHANGE           1158
#define ST_GRUPO_RE_PERSONCHANGE        1159
#define TXT_GRUPO_PERSONCHANGE          1160
#define ST_PERFIL_RE_PERSONCHANGE       1161
#define TXT_PERFIL_PERSONCHANGE         1162
#define LB_CHANGE_PERSON                1163
#define ST_TEXTONAMAS_CHANGE            1164
#define BM_IMAGE_PERSONCHANGE           1165
#define ST_IMAGE_RE_PERSONCHANGE        1166
#define BTN_OK_PERSONCHANGE             1167
#define CB_CIVIL_CHANGEPERSON           1168
#define CB_PERFIL_CHANGEPERSON          1169
#define CB_SEXO_CHANGEPERSON            1170
#define IDC_DATETIMEPICKER1             1171
#define DT_FECHA_CHANGEPERSON           1171
#define BTN_LOADNEWIMAGE_CHANGEPERSON   1172
#define BTN_OK_RE_CARNET                1173
#define ST_IDENTIDAD_RE_PERSONCHANGE    1173
#define LB_CURP_RE_CARNET               1174
#define TXT_IDENTIDAD_PERSONCHANGE      1174
#define LB_CLAVE_RE_CARNET              1175
#define CB_IDENTIDAD_CHANGEPERSON       1175
#define TXT_AP_RE_CARNET                1176
#define ST_AP_RE_CARNET                 1177
#define ST_AM_RE_CARNET                 1178
#define TXT_AM_RE_CARNET                1179
#define ST_NAME_RE_CARNET               1180
#define TXT_NAME_RE_CARNET              1181
#define ST_CURP_RE_CARNET               1182
#define TXT_CURP_RE_CARNET              1183
#define ST_RFC_RE_CARNET                1184
#define TXT_RFC_RE_CARNET               1185
#define ST_FECHA_RE_CARNET              1186
#define ST_CALLE_RE_CARNET              1187
#define TXT_CALLE_RE_CARNET             1188
#define ST_COL_RE_CARNET                1189
#define TXT_COLONIA_RE_CARNET           1190
#define ST_CIUDAD_RE_CARNET             1191
#define TXT_CIUDAD_RE_CARNET            1192
#define ST_ESTADO_RE_CARNET             1193
#define TXT_ESTADO_RE_CARNET            1194
#define ST_CIVIL_RE_CARNET              1195
#define ST_TELEFO_RE_CARNET             1196
#define TXT_TELEFO_RE_CARNET            1197
#define ST_SEXO_RE_CARNET               1198
#define ST_GRUPO_RE_CARNET              1199
#define ST_PERFIL_RE_CARNET             1200
#define ST_NOTA_1                       1201
#define ST_NOTA_2                       1202
#define ST_NOTA_3                       1203
#define ST_INFO_PER                     1204
#define ST_INFO_VAC                     1205
#define ST_IMAGE_RE_CARNET              1206
#define ST_CURP_CARNET                  1207
#define ST_CLAVE_CARNET                 1208
#define ST_ID_RE_CARNET                 1209
#define ST_TIPO_RE_CARNET               1210
#define TXT_TIPO_RE_CARNET              1211
#define ST_MARCA_RE_CARNET              1212
#define TXT_MARCA_RE_CARNET             1213
#define ST_DOSIS_RE_CARNET              1214
#define TXT_DOSIS_RE_CARNET             1215
#define ST_CLAVE_RE_CARNET              1216
#define TXT_CLAVE_RE_CARNET             1217
#define ST_DES_RE_CARNET                1218
#define TXT_DES_RE_CARNET               1219
#define ST_PRECIO_RE_CARNET             1220
#define TXT_PRECIO_RE_CARNET            1221
#define BM_IMAGE_RE_CARNET              1222
#define TXT_GRUPO_RE_CARNET             1223
#define PRINCIPAL_NOTA                  1224
#define ST_IDENTITI_RE_CARNET           1224
#define ST_INFO_PER_DELETE              1225
#define ST_INFO_VAC_DELETE              1226
#define ST_AP_RE_CARNET_DELETE          1227
#define TXT_AP_DELETE_CARNET            1228
#define ST_AM_DELETE_CARNET             1229
#define TXT_AM_DELETE_CARNET            1230
#define ST_NAME_DELETE_CARNET           1231
#define TXT_NAME_DELETE_CARNET          1232
#define ST_CURP_DELETE_CARNET           1233
#define TXT_CURP_DELETE_CARNET          1234
#define ST_RFC_DELETE_CARNET            1235
#define TXT_RFC_DELETE_CARNET           1236
#define ST_FECHA_DELETE_CARNET          1237
#define TXT_FECHA_DELETE_CARNET         1238
#define ST_CALLE_DELETE_CARNET          1239
#define TXT_CALLE_DELETE_CARNET         1240
#define ST_COL_DELETE_CARNET            1241
#define TXT_COLONIA_DELETE_CARNET       1242
#define ST_CIUDAD_DELETE_CARNET         1243
#define TXT_CIUDAD_DELETE_CARNET        1244
#define ST_ESTADO_DELETE_CARNET         1245
#define TXT_ESTADO_DELETE_CARNET        1246
#define ST_CIVIL_DELETE_CARNET          1247
#define TXT_CIVIL_DELETE_CARNET         1248
#define ST_TELEFO_DELETE_CARNET         1249
#define TXT_TELEFO_DELETE_CARNET        1250
#define ST_SEXO_DELETE_CARNET           1251
#define TXT_SEXO_DELETE_CARNET          1252
#define ST_GRUPO_DELETE_CARNET          1253
#define TXT_GRUPO_DELETE_CARNET         1254
#define ST_PERFIL_DELETE_CARNET         1255
#define TXT_PERFIL_DELETE_CARNET        1256
#define ST_CENTRO_DELETE_CARNET         1257
#define TXT_CENTRO_DELETE_CARNET        1258
#define ST_TIPO_DELETE_CARNET           1259
#define TXT_TIPO_DELETE_CARNET          1260
#define ST_MARCA_DELETE_CARNET          1261
#define TXT_MARCA_DELETE_CARNET         1262
#define ST_DOSIS_DELETE_CARNET          1263
#define TXT_DOSIS_DELETE_CARNET         1264
#define ST_CLAVE_DELETE_CARNET          1265
#define TXT_CLAVE_DELETE_CARNET         1266
#define ST_DES_DELETE_CARNET            1267
#define TXT_DES_DELETE_CARNET           1268
#define ST_PRECIO_DELETE_CARNET         1269
#define TXT_PRECIO_DELETE_CARNET        1270
#define ST_FECHAVACU1_DELETE_CARNET     1271
#define TXT_FECHAVACU1_DELETE_CARNET    1272
#define ST_FECHAVACU2_DELETE_CARNET     1273
#define TXT_FECHAVACU2_DELETE_CARNET    1274
#define ST_IMAGE_DELETE_CARNET          1275
#define BM_IMAGE_DELETE_CARNET          1276
#define TXT_SEXO_PERSONDELETE           1277
#define TXT_PERFIL_RE_CARNET            1278
#define TXT_PERFIL_PERSONDELETE         1279
#define TXT_SEXO_RE_CARNET              1280
#define TXT_IDENTIDAD_PERSONDELETE      1280
#define TXT_CIVIL_RE_CARNET             1281
#define TXT_FECHA_RE_CARNET             1282
#define TXT_FECHA_PERSONDELETE          1284
#define ST_BINARIA_CHANGE               1284
#define TXT_FECHAVACU2_RE_CARNET        1285
#define TXT_BINARIA_CHANGE              1285
#define ST_ID_DELETE_CARNET             1286
#define TXT_ID_DELETE_CARNET            1287
#define BTN_BINARIO_DELETE              1288
#define TXT_PERFIL_PERSONDELETE2        1289
#define BTN_BINARIO_CHANGE              1289
#define TXT_BINARIA_DELETE              1290
#define ST_INFO_PER_CHANGE              1290
#define ST_BINARIA_DELETE               1291
#define ST_INFO_VAC_CHANGE              1291
#define IDC_BUTTON2                     1292
#define ST_CURP_CARNET_CHANGE           1292
#define BTN_OK_DELETE_CARNET            1293
#define ST_CLAVE_CARNET_CHANGE          1294
#define LB_CURP_CHANGE_CARNET           1295
#define LB_CLAVE_CHANGE_CARNET          1296
#define BTN_OK_CHANGE_CARNET            1297
#define ST_AP_RE_CARNET_CHANGE          1298
#define TXT_AP_CHANGE_CARNET            1299
#define ST_AM_CHANGE_CARNET             1300
#define TXT_AM_CHANGE_CARNET            1301
#define ST_NAME_CHANGE_CARNET           1302
#define TXT_NAME_CHANGE_CARNET          1303
#define ST_CURP_CHANGE_CARNET           1304
#define TXT_CURP_CHANGE_CARNET          1305
#define ST_RFC_CHANGE_CARNET            1306
#define TXT_RFC_CHANGE_CARNET           1307
#define ST_FECHA_CHANGE_CARNET          1308
#define TXT_FECHA_CHANGE_CARNET         1309
#define ST_CALLE_CHANGE_CARNET          1310
#define TXT_CALLE_CHANGE_CARNET         1311
#define ST_COL_CHANGE_CARNET            1312
#define TXT_COLONIA_CHANGE_CARNET       1313
#define ST_CIUDAD_CHANGE_CARNET         1314
#define TXT_CIUDAD_CHANGE_CARNET        1315
#define ST_ESTADO_CHANGE_CARNET         1316
#define TXT_ESTADO_CHANGE_CARNET        1317
#define ST_CIVIL_CHANGE_CARNET          1318
#define TXT_CIVIL_CHANGE_CARNET         1319
#define ST_TELEFO_CHANGE_CARNET         1320
#define TXT_TELEFO_CHANGE_CARNET        1321
#define ST_SEXO_CHANGE_CARNET           1322
#define TXT_SEXO_CHANGE_CARNET          1323
#define ST_GRUPO_CHANGE_CARNET          1324
#define TXT_GRUPO_CHANGE_CARNET         1325
#define ST_PERFIL_CHANGE_CARNET         1326
#define TXT_PERFIL_CHANGE_CARNET        1327
#define ST_CENTRO_CHANGE_CARNET         1328
#define TXT_CENTRO_CHANGE_CARNET        1329
#define ST_TIPO_CHANGE_CARNET           1330
#define TXT_TIPO_CHANGE_CARNET          1331
#define ST_MARCA_CHANGE_CARNET          1332
#define TXT_MARCA_CHANGE_CARNET         1333
#define ST_DOSIS_CHANGE_CARNET          1334
#define TXT_DOSIS_CHANGE_CARNET         1335
#define ST_CLAVE_CHANGE_CARNET          1336
#define TXT_CLAVE_CHANGE_CARNET         1337
#define ST_DES_CHANGE_CARNET            1338
#define TXT_DES_CHANGE_CARNET           1339
#define ST_PRECIO_CHANGE_CARNET         1340
#define TXT_PRECIO_CHANGE_CARNET        1341
#define ST_FECHAVACU1_CHANGE_CARNET     1342
#define TXT_FECHAVACU1_CHANGE_CARNET    1343
#define ST_FECHAVACU2_CHANGE_CARNET     1344
#define TXT_FECHAVACU2_CHANGE_CARNET    1345
#define ST_IMAGE_CHANGE_CARNET          1346
#define BM_IMAGE_CHANGE_CARNET          1347
#define ST_ID_CHANGE_CARNET             1348
#define TXT_ID_CHANGE_CARNET            1349
#define ST_IDENTITI_CHANGE_CARNET       1350
#define TXT_IDENTITI_CHANGE_CARNET      1351
#define TXT_REPORTE_HEAPSORT            1352
#define BTN_OK_HEAPSORT                 1353
#define TXT_REPORTE_QUICKSORT           1354
#define BTN_OK_QUICKSORT                1355
#define LB_HEAPSORT_REPORT              1356
#define LB_QUICKSORT_REPORT             1357
#define ST_CENTRO_RE_CARNET             1400
#define MENU_PERSONAS_REGISTRO          40010
#define MENU_PERSONAS_BAJA              40011
#define MENU_PERSONAS_CAMBIO            40012
#define MENU_VACUNAS_REGISTRO           40013
#define MENU_VACUNAS_BAJA               40014
#define MENU_VACUNAS_CAMBIO             40015
#define MENU_CARNE_RE                   40016
#define MENU_CARNE_BAJA                 40017
#define MENU_CARNE_CAMBIO               40018
#define ID_PANTALLAPRINCIPAL            40019
#define MENU_PANTALLAPRINCIPAL          40020
#define BTN_MENU_REPORT_NAME            40023
#define BTN_MENU_REPORT_ID              40024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1358
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
